# Generated by Django 2.0.6 on 2018-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regisrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eljurUserId', models.CharField(max_length=300)),
                ('activationPhrase', models.CharField(max_length=600)),
            ],
        ),
    ]
