# Generated by Django 2.0.6 on 2018-06-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisrationdata',
            name='expires',
            field=models.CharField(default='0', max_length=30),
        ),
    ]
