# Generated by Django 2.0.6 on 2018-06-02 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_regisrationdata_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='regisrationdata',
            name='eljurLogin',
            field=models.CharField(default='none', max_length=300),
        ),
        migrations.AlterField(
            model_name='regisrationdata',
            name='activationPhrase',
            field=models.CharField(default='none', max_length=600),
        ),
        migrations.AlterField(
            model_name='regisrationdata',
            name='eljurUserId',
            field=models.CharField(default='none', max_length=300),
        ),
    ]
