# Generated by Django 2.0.7 on 2018-07-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_user_id', models.CharField(default='none', max_length=256)),
                ('eljur_user_id', models.CharField(default='none', max_length=256)),
            ],
        ),
        migrations.DeleteModel(
            name='users',
        ),
        migrations.RemoveField(
            model_name='regisrationdata',
            name='activationPhrase',
        ),
        migrations.RemoveField(
            model_name='regisrationdata',
            name='eljurLogin',
        ),
        migrations.RemoveField(
            model_name='regisrationdata',
            name='eljurUserId',
        ),
        migrations.AddField(
            model_name='regisrationdata',
            name='activation_phrase',
            field=models.CharField(default='none', max_length=512),
        ),
        migrations.AddField(
            model_name='regisrationdata',
            name='eljur_login',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AddField(
            model_name='regisrationdata',
            name='eljur_user_id',
            field=models.CharField(default='none', max_length=256),
        ),
        migrations.AlterField(
            model_name='regisrationdata',
            name='expires',
            field=models.IntegerField(default=0),
        ),
    ]
