# Generated by Django 2.0.7 on 2018-07-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20180721_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisrationdata',
            name='expires',
            field=models.BigIntegerField(default=0),
        ),
    ]
