# Generated by Django 2.0.7 on 2018-07-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20180727_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisrationdata',
            name='expires',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
