# Generated by Django 2.0.7 on 2018-07-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20180727_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regisrationdata',
            name='expires',
            field=models.CharField(default='0', max_length=512),
        ),
    ]
